### PR TITLE
Clarify the .min.gz size of VanJS, as most of the libraries are using…

### PR DESCRIPTION
**Pull request by Tao-VanJS**
… .min.gz

### CODE REVIEW

**Comment by TAR5** [comment]
It might be worthwhile to update all entries to use the gzipped size by default, and maybe add a note to the readme for contributors @adamghill

**Comment by adamghill** [comment]
Yep, makes sense!

**Comment by Tao-VanJS** [comment]
Hi @adamghill,

Could you let me know I could proceed with this PR?

**Comment by adamghill** [comment]
@Tao-VanJS I think I used the minified size for the libraries I added there so it can just be `0.8 KB`.

**Comment by Tao-VanJS** [comment]
@adamghill, to confirm, do you want me to just change it to `0.8kB`?

**Comment by adamghill** [comment]
@Tao-VanJS Yep, looks good! I will merge it in. Thanks for the PR. 👍

**Pull request merged**
